import { useState } from "react";
import { useAuth } from "@/contexts/AuthContext";
import { Github, Loader2, CheckCircle, Key } from "lucide-react";
import { toast } from "sonner";
import { useProject } from "@/contexts/ProjectContext";

export function GitHubPanel() {
  const { user, githubToken, setGithubToken } = useAuth();
  const { project } = useProject();
  const [repoName, setRepoName] = useState("");
  const [tokenInput, setTokenInput] = useState("");
  const [pushing, setPushing] = useState(false);
  const [pushed, setPushed] = useState(false);

  const saveToken = () => {
    if (tokenInput.trim()) {
      setGithubToken(tokenInput.trim());
      setTokenInput("");
      toast.success("GitHub token saved");
    }
  };

  const pushToGitHub = async () => {
    if (!githubToken || !project || !repoName.trim()) {
      toast.error("Missing token, project, or repo name");
      return;
    }

    setPushing(true);
    try {
      const createRes = await fetch("https://api.github.com/user/repos", {
        method: "POST",
        headers: {
          Authorization: `token ${githubToken}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          name: repoName,
          description: "Generated by Nero AI",
          private: false,
          auto_init: true,
        }),
      });

      if (!createRes.ok && createRes.status !== 422) {
        throw new Error("Failed to create repo");
      }

      // Get username from GitHub API
      const userRes = await fetch("https://api.github.com/user", {
        headers: { Authorization: `token ${githubToken}` },
      });
      const userData = await userRes.json();
      const fullName = `${userData.login}/${repoName}`;

      for (const file of project.files) {
        await fetch(
          `https://api.github.com/repos/${fullName}/contents/${file.path}`,
          {
            method: "PUT",
            headers: {
              Authorization: `token ${githubToken}`,
              "Content-Type": "application/json",
            },
            body: JSON.stringify({
              message: `Add ${file.path} via Nero AI`,
              content: btoa(unescape(encodeURIComponent(file.content))),
            }),
          }
        );
      }

      setPushed(true);
      toast.success(`Pushed to github.com/${fullName}`);
    } catch (err) {
      console.error(err);
      toast.error("Failed to push to GitHub");
    } finally {
      setPushing(false);
    }
  };

  if (!githubToken) {
    return (
      <div className="flex flex-col h-full bg-background p-4 gap-4">
        <div className="flex items-center gap-2">
          <Key className="w-5 h-5 text-foreground" />
          <h2 className="text-sm font-medium text-foreground">Connect GitHub</h2>
        </div>
        <p className="text-xs text-muted-foreground">
          Enter a GitHub Personal Access Token with <code className="font-mono text-foreground">repo</code> scope to push code.
        </p>
        <input
          type="password"
          value={tokenInput}
          onChange={(e) => setTokenInput(e.target.value)}
          placeholder="ghp_xxxxxxxxxxxxxxxxxxxx"
          className="w-full bg-nero-surface border border-border rounded-lg px-3 py-2.5 text-sm text-foreground placeholder:text-muted-foreground outline-none focus:ring-1 focus:ring-ring font-mono"
        />
        <button
          onClick={saveToken}
          disabled={!tokenInput.trim()}
          className="w-full flex items-center justify-center gap-2 h-11 rounded-lg bg-foreground text-background font-medium text-sm hover:opacity-90 transition-opacity disabled:opacity-40"
        >
          Save Token
        </button>
      </div>
    );
  }

  if (!project || project.files.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center h-full text-center px-6 gap-3">
        <Github className="w-10 h-10 text-muted-foreground" />
        <p className="text-sm text-muted-foreground">
          Generate some code first, then push it to GitHub.
        </p>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full bg-background p-4 gap-4">
      <div className="flex items-center gap-2">
        <Github className="w-5 h-5 text-foreground" />
        <h2 className="text-sm font-medium text-foreground">Push to GitHub</h2>
      </div>

      <p className="text-xs text-muted-foreground">
        Create a new repo or push to an existing one. {project.files.length} file(s) ready.
      </p>

      <input
        value={repoName}
        onChange={(e) => setRepoName(e.target.value)}
        placeholder="Repository name"
        className="w-full bg-nero-surface border border-border rounded-lg px-3 py-2.5 text-sm text-foreground placeholder:text-muted-foreground outline-none focus:ring-1 focus:ring-ring"
      />

      <button
        onClick={pushToGitHub}
        disabled={pushing || !repoName.trim()}
        className="w-full flex items-center justify-center gap-2 h-11 rounded-lg bg-foreground text-background font-medium text-sm hover:opacity-90 transition-opacity disabled:opacity-40"
      >
        {pushing ? (
          <Loader2 className="w-4 h-4 animate-spin" />
        ) : pushed ? (
          <CheckCircle className="w-4 h-4" />
        ) : (
          <Github className="w-4 h-4" />
        )}
        {pushing ? "Pushing..." : pushed ? "Pushed!" : "Push to GitHub"}
      </button>

      {pushed && (
        <p className="text-xs text-center text-muted-foreground">
          Check your GitHub repos for the new repository.
        </p>
      )}
    </div>
  );
}
