import { useState } from "react";
import { useAuth } from "@/contexts/AuthContext";
import { Github, Loader2, CheckCircle, Key, Download, FolderInput } from "lucide-react";
import { toast } from "sonner";
import { useProject, ProjectFile } from "@/contexts/ProjectContext";

export function GitHubPanel() {
  const { githubToken, setGithubToken } = useAuth();
  const { project, addFile, addConsoleLog } = useProject();
  const [repoName, setRepoName] = useState("");
  const [tokenInput, setTokenInput] = useState("");
  const [pushing, setPushing] = useState(false);
  const [pushed, setPushed] = useState(false);
  const [importRepo, setImportRepo] = useState("");
  const [importing, setImporting] = useState(false);
  const [mode, setMode] = useState<"push" | "import">("push");

  const saveToken = () => {
    if (tokenInput.trim()) {
      setGithubToken(tokenInput.trim());
      setTokenInput("");
      toast.success("GitHub token saved");
    }
  };

  const pushToGitHub = async () => {
    if (!githubToken || !project || !repoName.trim()) {
      toast.error("Missing token, project, or repo name");
      return;
    }

    setPushing(true);
    try {
      const createRes = await fetch("https://api.github.com/user/repos", {
        method: "POST",
        headers: { Authorization: `token ${githubToken}`, "Content-Type": "application/json" },
        body: JSON.stringify({ name: repoName, description: "Generated by Nero AI", private: false, auto_init: true }),
      });

      if (!createRes.ok && createRes.status !== 422) throw new Error("Failed to create repo");

      const userRes = await fetch("https://api.github.com/user", { headers: { Authorization: `token ${githubToken}` } });
      const userData = await userRes.json();
      const fullName = `${userData.login}/${repoName}`;

      for (const file of project.files) {
        await fetch(`https://api.github.com/repos/${fullName}/contents/${file.path}`, {
          method: "PUT",
          headers: { Authorization: `token ${githubToken}`, "Content-Type": "application/json" },
          body: JSON.stringify({ message: `Add ${file.path} via Nero AI`, content: btoa(unescape(encodeURIComponent(file.content))) }),
        });
      }

      setPushed(true);
      toast.success(`Pushed to github.com/${fullName}`);
    } catch (err) {
      console.error(err);
      toast.error("Failed to push to GitHub");
    } finally {
      setPushing(false);
    }
  };

  const importFromGitHub = async () => {
    if (!githubToken || !importRepo.trim()) {
      toast.error("Enter a repo like owner/repo");
      return;
    }

    setImporting(true);
    try {
      const repo = importRepo.trim().replace(/^https?:\/\/github\.com\//, "").replace(/\/$/, "");
      
      // Try to get default branch first
      const repoRes = await fetch(`https://api.github.com/repos/${repo}`, {
        headers: { Authorization: `token ${githubToken}`, Accept: "application/vnd.github.v3+json" },
      });
      
      if (!repoRes.ok) {
        const errData = await repoRes.json().catch(() => ({}));
        throw new Error(errData.message || `Repository not found (${repoRes.status})`);
      }
      
      const repoData = await repoRes.json();
      const defaultBranch = repoData.default_branch || "main";
      
      addConsoleLog(`📡 Fetching tree from ${repo} (branch: ${defaultBranch})...`);

      const treeRes = await fetch(`https://api.github.com/repos/${repo}/git/trees/${defaultBranch}?recursive=1`, {
        headers: { Authorization: `token ${githubToken}`, Accept: "application/vnd.github.v3+json" },
      });

      if (!treeRes.ok) {
        throw new Error(`Could not fetch repo tree (${treeRes.status})`);
      }
      
      const treeData = await treeRes.json();

      const blobs = (treeData.tree || []).filter(
        (item: any) => item.type === "blob" && 
          !item.path.includes("node_modules/") && 
          !item.path.includes(".git/") &&
          !item.path.includes("dist/") &&
          !item.path.includes(".lock") &&
          item.size < 100000 // Skip files > 100KB
      );

      const textExtensions = [".html", ".css", ".js", ".ts", ".tsx", ".jsx", ".json", ".md", ".txt", ".svg", ".xml", ".yaml", ".yml", ".env.example", ".sh", ".py", ".rb", ".go", ".rs", ".java", ".php", ".vue", ".svelte"];
      const textBlobs = blobs
        .filter((b: any) => textExtensions.some((ext) => b.path.endsWith(ext)))
        .slice(0, 80);

      addConsoleLog(`📥 Importing ${textBlobs.length} files from ${repo}...`);

      let imported = 0;
      let failed = 0;
      
      // Batch fetch in groups of 5 for speed
      for (let i = 0; i < textBlobs.length; i += 5) {
        const batch = textBlobs.slice(i, i + 5);
        const results = await Promise.allSettled(
          batch.map(async (blob: any) => {
            const contentRes = await fetch(`https://api.github.com/repos/${repo}/contents/${blob.path}?ref=${defaultBranch}`, {
              headers: { Authorization: `token ${githubToken}`, Accept: "application/vnd.github.v3+json" },
            });
            if (!contentRes.ok) throw new Error(`Failed to fetch ${blob.path}`);
            const contentData = await contentRes.json();

            let content = "";
            if (contentData.encoding === "base64" && contentData.content) {
              try {
                content = decodeURIComponent(escape(atob(contentData.content.replace(/\n/g, ""))));
              } catch {
                // Fallback: try simple atob
                try { content = atob(contentData.content.replace(/\n/g, "")); } catch { content = contentData.content; }
              }
            } else {
              content = contentData.content || "";
            }

            const ext = blob.path.split(".").pop() || "text";
            const langMap: Record<string, string> = {
              html: "html", css: "css", js: "javascript", ts: "typescript", tsx: "tsx", jsx: "jsx",
              json: "json", md: "markdown", py: "python", rb: "ruby", go: "go", rs: "rust",
              java: "java", php: "php", vue: "vue", svelte: "svelte", sh: "bash", yaml: "yaml", yml: "yaml"
            };

            const file: ProjectFile = {
              id: crypto.randomUUID(),
              name: blob.path.split("/").pop() || blob.path,
              path: blob.path,
              content,
              language: langMap[ext] || ext,
            };
            addFile(file);
            return file;
          })
        );
        
        results.forEach((r) => { if (r.status === "fulfilled") imported++; else failed++; });
        addConsoleLog(`  📄 Progress: ${imported}/${textBlobs.length} files...`);
      }

      addConsoleLog(`✅ Imported ${imported} files from ${repo}${failed > 0 ? ` (${failed} failed)` : ""}`);
      toast.success(`Imported ${imported} files from ${repo}`);
    } catch (err) {
      console.error("GitHub import error:", err);
      toast.error(`Import failed: ${err instanceof Error ? err.message : "Unknown error"}`);
      addConsoleLog(`❌ Import failed: ${err instanceof Error ? err.message : "Unknown"}`);
    } finally {
      setImporting(false);
    }
  };

  if (!githubToken) {
    return (
      <div className="flex flex-col h-full bg-background p-4 gap-4">
        <div className="flex items-center gap-2">
          <Key className="w-5 h-5 text-foreground" />
          <h2 className="text-sm font-medium text-foreground">Connect GitHub</h2>
        </div>
        <p className="text-xs text-muted-foreground">
          Enter a GitHub Personal Access Token with <code className="font-mono text-foreground">repo</code> scope.
        </p>
        <input
          type="password"
          value={tokenInput}
          onChange={(e) => setTokenInput(e.target.value)}
          placeholder="ghp_xxxxxxxxxxxxxxxxxxxx"
          className="w-full bg-nero-surface border border-border rounded-lg px-3 py-2.5 text-sm text-foreground placeholder:text-muted-foreground outline-none focus:ring-1 focus:ring-ring font-mono"
        />
        <button onClick={saveToken} disabled={!tokenInput.trim()} className="w-full flex items-center justify-center gap-2 h-11 rounded-lg bg-foreground text-background font-medium text-sm hover:opacity-90 transition-opacity disabled:opacity-40">
          Save Token
        </button>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full bg-background p-4 gap-4">
      <div className="flex rounded-lg border border-border overflow-hidden">
        <button
          onClick={() => setMode("push")}
          className={`flex-1 flex items-center justify-center gap-1.5 py-2 text-xs font-medium transition-colors ${mode === "push" ? "bg-nero-tab-active text-foreground" : "text-muted-foreground hover:text-foreground"}`}
        >
          <Github className="w-3.5 h-3.5" /> Push
        </button>
        <button
          onClick={() => setMode("import")}
          className={`flex-1 flex items-center justify-center gap-1.5 py-2 text-xs font-medium transition-colors ${mode === "import" ? "bg-nero-tab-active text-foreground" : "text-muted-foreground hover:text-foreground"}`}
        >
          <FolderInput className="w-3.5 h-3.5" /> Import
        </button>
      </div>

      {mode === "push" ? (
        <>
          <p className="text-xs text-muted-foreground">
            {project?.files.length || 0} file(s) ready to push.
          </p>
          <input
            value={repoName}
            onChange={(e) => setRepoName(e.target.value)}
            placeholder="Repository name"
            className="w-full bg-nero-surface border border-border rounded-lg px-3 py-2.5 text-sm text-foreground placeholder:text-muted-foreground outline-none focus:ring-1 focus:ring-ring"
          />
          <button
            onClick={pushToGitHub}
            disabled={pushing || !repoName.trim() || !project?.files.length}
            className="w-full flex items-center justify-center gap-2 h-11 rounded-lg bg-foreground text-background font-medium text-sm hover:opacity-90 transition-opacity disabled:opacity-40"
          >
            {pushing ? <Loader2 className="w-4 h-4 animate-spin" /> : pushed ? <CheckCircle className="w-4 h-4" /> : <Github className="w-4 h-4" />}
            {pushing ? "Pushing..." : pushed ? "Pushed!" : "Push to GitHub"}
          </button>
        </>
      ) : (
        <>
          <p className="text-xs text-muted-foreground">
            Import files from a GitHub repo. Supports owner/repo or full URL.
          </p>
          <input
            value={importRepo}
            onChange={(e) => setImportRepo(e.target.value)}
            placeholder="owner/repo or https://github.com/owner/repo"
            className="w-full bg-nero-surface border border-border rounded-lg px-3 py-2.5 text-sm text-foreground placeholder:text-muted-foreground outline-none focus:ring-1 focus:ring-ring font-mono"
          />
          <button
            onClick={importFromGitHub}
            disabled={importing || !importRepo.trim()}
            className="w-full flex items-center justify-center gap-2 h-11 rounded-lg bg-foreground text-background font-medium text-sm hover:opacity-90 transition-opacity disabled:opacity-40"
          >
            {importing ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
            {importing ? "Importing..." : "Import Repo"}
          </button>
        </>
      )}

      <button
        onClick={() => { setGithubToken(null); toast.info("Token removed"); }}
        className="text-xs text-muted-foreground hover:text-foreground transition-colors text-center"
      >
        Disconnect GitHub
      </button>
    </div>
  );
}
